// jobportal-angular/src/app/jobseeker-login/jobseeker-login.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { JobSeeker } from '../jobSeeker';
import { JobSeekerDataService } from '../service/jobseeker-data.service';
import { JobseekerService } from '../service/jobseeker.service';

@Component({
  selector: 'app-jobseeker-login',
  templateUrl: './jobseeker-login.component.html',
  styleUrls: ['./jobseeker-login.component.css'],
})
export class JobseekerLoginComponent {
  constructor(
    private jobSeekerService: JobseekerService,
    private router: Router,
    public jobSeekerData: JobSeekerDataService
  ) {}

  public onLoginJobSeeker(loginForm: NgForm): void {
    if (this.validateEmail() && this.validatePassword()) {
      this.jobSeekerService
        .loginJobSeeker(loginForm.value.email, loginForm.value.password)
        .subscribe(
          (response: JobSeeker[]) => {
            if (response.length == 0) {
              // if response is empty, incorrect email or password
              this.incorrectInputs = true;
            } else {
              console.log(response[0]);
              this.jobSeekerData.currentJobSeeker = response[0];
              console.log(this.jobSeekerData.currentJobSeeker.);
              this.jobSeekerData.loggedIn = true;
              this.router.navigate(['jobseeker/home']);
            }
          },
          (error: HttpErrorResponse) => {
            alert(error.message);
          }
        );
    }
  }

  public incorrectInputs: boolean = false;

  public email: string = '';
  public emailError: boolean = false;

  public password: string = '';
  public passwordError: boolean = false;

  validateEmail(): any {
    if (this.email == '') {
      this.emailError = false;
    } else if (
      !/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
        this.email.toLowerCase()
      )
    ) {
      this.emailError = true;
      return false;
    } else {
      this.emailError = false;
      return true;
    }
  }

  validatePassword(): any {
    if (this.password.length < 7 && this.password != '') {
      this.passwordError = true;
      return false;
    } else {
      this.passwordError = false;
      return true;
    }
  }
}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>JobSeeker Login</title>
  </head>
  <body>
    <div class="modal-conatiner">
      <h2>Job-Seeker Login</h2>
      <h2 *ngIf="incorrectInputs">
        Email/password is incorrect... Please try again
      </h2>

      <form
        name="registrationForm"
        id="form"
        #loginForm="ngForm"
        (ngSubmit)="onLoginJobSeeker(loginForm)"
        class="formLogin"
      >
        <div class="input-control">
          <div
            id="email-error"
            class="error"
            *ngIf="emailInput.touched && emailError"
          >
            <small>Please enter a valid email</small>
          </div>
          <div id="email-error"></div>
          <div class="user-box">
            <input
              ngModel
              type="text"
              name="email"
              required
              class="inputField emailField"
              id="emailId"
              #emailInput="ngModel"
              [(ngModel)]="email"
              (keyup)="validateEmail()"
            />
            <label class="label emailLabel">Email</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="password-error"
            class="error"
            *ngIf="passwordInput.touched && passwordError"
          >
            <small>Please enter a password</small>
          </div>
          <div id="password-error"></div>
          <div class="user-box">
            <input
              ngModel
              type="text"
              name="password"
              required
              class="inputField passwordField"
              id="passwordId"
              #passwordInput="ngModel"
              [(ngModel)]="password"
              (keyup)="validatePassword()"
            />
            <label class="label passwordLabel">Password</label>
          </div>
        </div>

        <button
          class="submit-btn"
          role="button"
          type="submit"
          [disabled]="loginForm.invalid"
        >
          Login
        </button>
      </form>
    </div>
  </body>
</html>

// jobportal-react/src/components/Jobseeker/JobseekerLogin.jsx
import React, { useState } from "react";
import styles from "../../styles/JobseekerRegister.module.css";
import { useNavigate } from "react-router-dom";
import { loginJobSeekerAPI } from "../../utils/fetchFromAPI";

const JobseekerLogin = () => {
  let navigate = useNavigate();

  const [formData, setFormData] = useState({});
  let [emailError, setEmailError] = useState(false);
  let [passwordError, setPasswordError] = useState(false);
  let [inputError, setInputError] = useState(false);

  const handleSubmit = async (e) => {
    if (!emailError && !passwordError) {
      try {
        e.preventDefault();
        const response = await loginJobSeekerAPI(
          formData.email,
          formData.password
        );

        if (response.length == 0) {
          setInputError(true);
        } else {
          window.localStorage.setItem(
            "jobSeekerData",
            JSON.stringify(response)
          );
          window.localStorage.setItem("isLoggedIn", JSON.stringify(true));
          console.log(response);
          setInputError(false);
          navigate("/jobseeker/home");
        }
      } catch (error) {}
    } else {
      e.preventDefault();
    }
  };

  const handleChange = (e) => {
    if (e.target.name === "email") {
      validateEmail(e.target.value);
    } else if (e.target.name === "password") {
      validatePassword(e.target.value);
    }

    setFormData((prevFormData) => ({
      ...prevFormData,
      [e.target.name]: e.target.value,
    }));
  };

  const validateEmail = (email) => {
    if (email === "") {
      setEmailError(false);
    } else if (
      !/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
        email.toLowerCase()
      )
    ) {
      setEmailError(true);
    } else {
      setEmailError(false);
    }
  };

  const validatePassword = (password) => {
    if (password.length < 7 && password !== "") {
      setPasswordError(true);
    } else {
      setPasswordError(false);
    }
  };

  return (
    <div className={styles.modalContainer}>
      <h2>JobSeeker Login</h2>
      {inputError ? (
        <h2>Email/password is incorrect... Please try again</h2>
      ) : (
        <div />
      )}
      <form onSubmit={handleSubmit}>
        <div className="inputControl">
          {emailError ? (
            <div className="error">
              <div className={styles.error}>
                <p>Please enter a valid email</p>
              </div>
            </div>
          ) : (
            <div></div>
          )}

          <div className={styles.inputBox}>
            <input
              type="text"
              className={styles.inputField}
              name="email"
              required
              onChange={handleChange}
            />
            <label className={styles.label}>Email:</label>
          </div>
        </div>

        <div className="inputControl">
          {passwordError ? (
            <div className="error">
              <div className={styles.error}>
                <p>Please enter a valid password</p>
              </div>
            </div>
          ) : (
            <div></div>
          )}

          <div className={styles.inputBox}>
            <input
              type="text"
              className={styles.inputField}
              name="password"
              required
              onChange={handleChange}
            />
            <label className={styles.label}>Password:</label>
          </div>
        </div>

        <button className={styles.submitBtn} type="submit">
          Login
        </button>
      </form>
    </div>
  );
};

export default JobseekerLogin;
