// jobportal-react/src/components/Jobseeker/Jobseeker-Profile/JobseekerProfile.jsx
import React, { useState, useEffect } from "react";
import styles from "../../../styles/JobseekerRegister.module.css";
import {
  editProfileAPI,
  checkUniqueEmailAPI,
} from "../../../utils/fetchFromAPI";
import { useNavigate } from "react-router-dom";
import Navbar from "../../Navbar";

const JobseekerProfile = (props) => {
  const [formData, setFormData] = useState({});

  let [firstName, setFirstName] = useState("");
  let [lastName, setLastName] = useState("");
  let [email, setEmail] = useState("");
  let [phone, setPhone] = useState("");
  let [password, setPassword] = useState("");

  let [firstNameError, setFirstNameError] = useState(false);
  let [lastNameError, setLastNameError] = useState(false);
  let [emailError, setEmailError] = useState(false);
  let [phoneError, setPhoneError] = useState(false);
  let [passwordError, setPasswordError] = useState(false);
  let [uniqueEmailReturn, setUniqueEmailReturn] = useState([]);
  let [uniqueEmailError, setUniqueEmailError] = useState(false);

  useEffect(() => {
    const jobSeekerData = JSON.parse(
      window.localStorage.getItem("jobSeekerData")
    )[0];
    console.log(jobSeekerData);

    setFormData(jobSeekerData);
    setFirstName(jobSeekerData.firstName);
    setLastName(jobSeekerData.lastName);
    setEmail(jobSeekerData.email);
    setPhone(jobSeekerData.phone);
    setPassword(jobSeekerData.password);
  }, []);

  let navigate = useNavigate();

  const handleChange = (e) => {
    if (e.target.name === "firstName") {
      setFirstName(e.target.value);
      validateFirstName(e.target.value);
    } else if (e.target.name === "lastName") {
      setLastName(e.target.value);
      validateLastName(e.target.value);
    } else if (e.target.name === "email") {
      setEmail(e.target.value);
      validateEmail(e.target.value);
    } else if (e.target.name === "phone") {
      setPhone(e.target.value);
      validatePhone(e.target.value);
    } else if (e.target.name === "password") {
      setPassword(e.target.value);
      validatePassword(e.target.value);
    }

    setFormData((prevFormData) => ({
      ...prevFormData,
      [e.target.name]: e.target.value,
    }));
  };

  const handleSubmit = (e) => {
    const getUpdatedProfile = async () => {
      const response = await editProfileAPI(formData);
      console.log(response);
      window.localStorage.setItem("jobSeekerData", JSON.stringify([response]));
    };

    try {
      if (
        !firstNameError &&
        !lastNameError &&
        !emailError &&
        !phoneError &&
        !passwordError &&
        uniqueEmailTest()
      ) {
        e.preventDefault();
        getUpdatedProfile();
        navigate("/jobseeker/profilesuccess");
      } else {
        e.preventDefault();
        console.log("submit fail");
      }
    } catch (error) {
      console.log(error);
    }
  };

  const uniqueEmail = async (email) => {
    try {
      const response = await checkUniqueEmailAPI(email);
      setUniqueEmailReturn(response);
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  };

  const uniqueEmailTest = () => {
    if (uniqueEmailReturn.length == 0) {
      setUniqueEmailError(false);
      console.log("pass1");
      return true;
    } else if (uniqueEmailReturn[0].id == formData.id) {
      setUniqueEmailError(false);
      console.log("pass2");
      return true;
    } else {
      setUniqueEmailError(true);
      console.log("fail");
      return false;
    }
  };

  const validateFirstName = (firstName) => {
    if (/\d/.test(firstName)) {
      setFirstNameError(true);
    } else {
      setFirstNameError(false);
    }
  };

  const validateLastName = (lastName) => {
    if (/\d/.test(lastName)) {
      setLastNameError(true);
    } else {
      setLastNameError(false);
    }
  };

  const validateEmail = (email) => {
    if (email === "") {
      setEmailError(false);
    } else if (
      !/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
        email.toLowerCase()
      )
    ) {
      setEmailError(true);
    } else {
      setEmailError(false);
      uniqueEmail(email);
    }
  };

  const validatePhone = (phone) => {
    if (/^\d+$/.test(phone) || phone === "") {
      setPhoneError(false);
    } else {
      setPhoneError(true);
    }
  };

  const validatePassword = (password) => {
    if (password.length < 7 && password !== "") {
      setPasswordError(true);
    } else {
      setPasswordError(false);
    }
  };

  return (
    <>
      <Navbar />
      <div className={styles.modalContainer}>
        <h2>Update Profile</h2>
        {uniqueEmailError ? <h2>Email taken... Please try again</h2> : <div />}

        <form onSubmit={handleSubmit}>
          <div className="inputControl">
            {firstNameError ? (
              <div className="error">
                <div className={styles.error}>
                  <p>Please enter a valid first name</p>
                </div>
              </div>
            ) : (
              <div></div>
            )}

            <div className={styles.inputBox}>
              <input
                type="text"
                className={styles.inputField}
                name="firstName"
                required
                onChange={handleChange}
                value={firstName}
              />
              <label className={styles.label}>First Name:</label>
            </div>
          </div>

          <div className="inputControl">
            {lastNameError ? (
              <div className="error">
                <div className={styles.error}>
                  <p>Please enter a valid last name</p>
                </div>
              </div>
            ) : (
              <div></div>
            )}

            <div className={styles.inputBox}>
              <input
                type="text"
                className={styles.inputField}
                name="lastName"
                required
                onChange={handleChange}
                value={lastName}
              />
              <label className={styles.label}>Last Name:</label>
            </div>
          </div>

          <div className="inputControl">
            {emailError ? (
              <div className="error">
                <div className={styles.error}>
                  <p>Please enter a valid email</p>
                </div>
              </div>
            ) : (
              <div></div>
            )}

            <div className={styles.inputBox}>
              <input
                type="text"
                className={styles.inputField}
                name="email"
                required
                onChange={handleChange}
                value={email}
              />
              <label className={styles.label}>Email:</label>
            </div>
          </div>

          <div className="inputControl">
            {phoneError ? (
              <div className="error">
                <div className={styles.error}>
                  <p>Please enter a valid phone number</p>
                </div>
              </div>
            ) : (
              <div></div>
            )}

            <div className={styles.inputBox}>
              <input
                type="text"
                className={styles.inputField}
                name="phone"
                required
                onChange={handleChange}
                value={phone}
              />
              <label className={styles.label}>Phone Number:</label>
            </div>
          </div>

          <div className="inputControl">
            {passwordError ? (
              <div className="error">
                <div className={styles.error}>
                  <p>Please enter a valid password</p>
                </div>
              </div>
            ) : (
              <div></div>
            )}

            <div className={styles.inputBox}>
              <input
                type="text"
                className={styles.inputField}
                name="password"
                required
                onChange={handleChange}
                value={password}
              />
              <label className={styles.label}>Password:</label>
            </div>
          </div>

          <button className={styles.submitBtn} type="submit">
            Update Profile
          </button>
        </form>
      </div>
    </>
  );
};

export default JobseekerProfile;

// jobportal-angular/src/app/jobseeker-profile/jobseeker-profile.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { JobSeeker } from '../jobSeeker';
import { JobSeekerDataService } from '../service/jobseeker-data.service';
import { JobseekerService } from '../service/jobseeker.service';

@Component({
  selector: 'app-jobseeker-profile',
  templateUrl: './jobseeker-profile.component.html',
  styleUrls: ['./jobseeker-profile.component.css'],
})
export class JobseekerProfileComponent {
  constructor(
    public jobSeekerService: JobseekerService,
    private router: Router,
    public jobSeekerData: JobSeekerDataService
  ) {}

  public onEditJobSeeker(editForm: NgForm): void {
    if (
      this.validateFirstName(editForm.value.firstName) &&
      this.validateLastName(editForm.value.lastName) &&
      this.validateEmail(editForm.value.email) &&
      this.validatePhone(editForm.value.phone) &&
      this.validatePassword(editForm.value.password) &&
      this.uniqueEmailTest(editForm.value.email)
    ) {
      this.jobSeekerData.currentJobSeeker = editForm.value;

      this.jobSeekerService.editJobSeeker(editForm.value).subscribe(
        (response: JobSeeker) => {
          this.router.navigate(['jobseeker/profile/success']);
        },
        (error: HttpErrorResponse) => {
          alert(error.message);
        }
      );
    }
  }

  public uniqueEmail(emailInput: string): any {
    this.jobSeekerService.checkUniqueEmail(emailInput).subscribe(
      (response: JobSeeker[]) => {
        this.uniqueEmailReturn = response;
      },
      (error: HttpErrorResponse) => {
        console.log('uniqueEmail error fail');
        this.uniqueEmailText = false;
        return false;
        alert(error.message);
      }
    );
  }

  public uniqueEmailTest(emailValue: string): boolean {
    if (this.uniqueEmailReturn?.length == 0) {
      console.log('uniqueEmail pass');
      this.uniqueEmailText = false;
      return true;
    } else if (
      this.uniqueEmailReturn![0].id ==
        this.jobSeekerData.currentJobSeeker?.id &&
      this.uniqueEmailReturn![0].email == emailValue
    ) {
      this.uniqueEmailText = false;
      return true;
    } else {
      this.uniqueEmailText = true;
      return false;
    }
  }

  //validation
  public uniqueEmailReturn?: JobSeeker[];
  public jobSeekerInput?: JobSeeker;

  public firstNameError: boolean = false;

  public lastNameError: boolean = false;

  public emailError: boolean = false;

  public phoneError: boolean = false;

  public passwordError: boolean = false;

  public formValid: boolean = false;

  public uniqueEmailText: boolean = false;

  validateFirstName(firstNameInput: string): boolean {
    if (/\d/.test(firstNameInput)) {
      this.firstNameError = true;
      return false;
    } else {
      console.log('first name pass');
      this.firstNameError = false;
      return true;
    }
  }

  validateLastName(lastNameInput: string): boolean {
    if (/\d/.test(lastNameInput)) {
      this.lastNameError = true;
      return false;
    } else {
      console.log('last name pass');
      this.lastNameError = false;
      return true;
    }
  }

  validateEmail(emailInput: string): any {
    if (emailInput == '') {
      this.emailError = false;
    } else if (
      !/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
        emailInput.toLowerCase()
      )
    ) {
      this.emailError = true;
      return false;
    } else {
      this.uniqueEmail(emailInput);
      this.emailError = false;
      return true;
    }
  }

  validatePhone(phoneInput: string): any {
    if (!/\d/.test(phoneInput) && phoneInput != '') {
      this.phoneError = true;
      return false;
    } else {
      console.log('phone pass');

      this.phoneError = false;
      return true;
    }
  }

  validatePassword(passwordInput: string): any {
    if (passwordInput.length < 7 && passwordInput != '') {
      this.passwordError = true;
      return false;
    } else {
      console.log('password pass');

      this.passwordError = false;
      return true;
    }
  }
}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Job Seeker Profile</title>
  </head>
  <body>
    <div class="modal-conatiner">
      <h2>JobSeeker Edit Profile</h2>
      <h2 *ngIf="uniqueEmailText">Email taken... Please try again</h2>

      <form
        name="editForm"
        id="form"
        #editForm="ngForm"
        (ngSubmit)="onEditJobSeeker(editForm)"
        class="formRegister"
      >
        <input
          type="hidden"
          ngModel="{{ jobSeekerData.currentJobSeeker?.id }}"
          name="id"
        />

        <div class="input-control">
          <div
            id="firstName-error"
            class="error"
            *ngIf="fname.touched && firstNameError"
          >
            <small>Please enter a valid first name</small>
          </div>
          <div class="user-box">
            <input
              type="text"
              ngModel="{{ jobSeekerData.currentJobSeeker?.firstName }}"
              #fname="ngModel"
              name="firstName"
              required
              class="inputField firstNameField"
              id="firstNameId"
              (keyup)="validateFirstName(editForm.value.firstName)"
            />
            <label class="label firstNameLabel">First Name</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="lastName-error"
            class="error"
            *ngIf="lname.touched && lastNameError"
          >
            <small>Please enter a valid last name</small>
          </div>
          <div id="lastName-error"></div>
          <div class="user-box">
            <input
              ngModel="{{ jobSeekerData.currentJobSeeker?.lastName }}"
              type="text"
              name="lastName"
              required
              class="inputField lastNameField"
              id="lastNameId"
              #lname="ngModel"
              (keyup)="validateLastName(editForm.value.lastName)"
            />
            <label class="label lastNameLabel">Last Name</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="email-error"
            class="error"
            *ngIf="emailInput.touched && emailError"
          >
            <small>Please enter a valid email</small>
          </div>
          <div id="email-error"></div>
          <div class="user-box">
            <input
              ngModel="{{ jobSeekerData.currentJobSeeker?.email }}"
              type="text"
              name="email"
              required
              class="inputField emailField"
              id="emailId"
              #emailInput="ngModel"
              (keyup)="validateEmail(editForm.value.email)"
            />
            <label class="label emailLabel">Email</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="phone-error"
            class="error"
            *ngIf="phoneInput.touched && phoneError"
          >
            <small>Please enter a valid phone number</small>
          </div>
          <div id="phone-error"></div>
          <div class="user-box">
            <input
              ngModel="{{ jobSeekerData.currentJobSeeker?.phone }}"
              type="text"
              name="phone"
              required
              class="inputField phoneField"
              id="phoneId"
              #phoneInput="ngModel"
              (keyup)="validatePhone(editForm.value.phone)"
            />
            <label class="label phoneLabel">Phone Number</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="password-error"
            class="error"
            *ngIf="passwordInput.touched && passwordError"
          >
            <small>Please enter at-least 7 characters</small>
          </div>
          <div id="password-error"></div>
          <div class="user-box">
            <input
              ngModel="{{ jobSeekerData.currentJobSeeker?.password }}"
              type="text"
              name="password"
              required
              class="inputField passwordField"
              id="passwordId"
              #passwordInput="ngModel"
              (keyup)="validatePassword(editForm.value.password)"
            />
            <label class="label passwordLabel">Password</label>
          </div>
        </div>

        <button
          class="submit-btn"
          role="button"
          type="submit"
          [disabled]="editForm.invalid"
        >
          Update
        </button>
      </form>
    </div>
  </body>
</html>
