// jobportal-angular/src/app/jobseeker-register/jobseeker-register.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';

@Component({
  selector: 'app-jobseeker-register',
  templateUrl: './jobseeker-register.component.html',
  styleUrls: ['./jobseeker-register.component.css'],
})
export class JobseekerRegisterComponent {
  public onRegisterJobSeeker(addForm: NgForm): void {
    if (
      this.validateFirstName() &&
      this.validateLastName() &&
      this.validateEmail() &&
      this.validatePhone() &&
      this.validatePassword()
    ) {
    }
  }

  //validation
  public firstName: string = '';
  public firstNameError: boolean = false;

  public lastName: string = '';
  public lastNameError: boolean = false;

  public email: string = '';
  public emailError: boolean = false;

  public phone: string = '';
  public phoneError: boolean = false;

  public password: string = '';
  public passwordError: boolean = false;

  public formValid: boolean = false;

  validateFirstName(): boolean {
    if (/\d/.test(this.firstName)) {
      this.firstNameError = true;
      return false;
    } else {
      this.firstNameError = false;
      return true;
    }
  }

  validateLastName(): boolean {
    if (/\d/.test(this.lastName)) {
      this.lastNameError = true;
      return false;
    } else {
      this.lastNameError = false;
      return true;
    }
  }

  validateEmail(): any {
    if (this.email == '') {
      this.emailError = false;
    } else if (
      !/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
        this.email.toLowerCase()
      )
    ) {
      this.emailError = true;
      return false;
    } else {
      this.emailError = false;
      return true;
    }
  }

  validatePhone(): any {
    if (!/\d/.test(this.phone) && this.phone != '') {
      this.phoneError = true;
      return false;
    } else {
      this.phoneError = false;
      return true;
    }
  }

  validatePassword(): any {
    if (this.password.length < 7 && this.password != '') {
      this.passwordError = true;
      return false;
    } else {
      this.passwordError = false;
      return true;
    }
  }
}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Job Seeker Register</title>
  </head>
  <body>
    <div class="modal-conatiner">
      <h2>JobSeeker Register</h2>

      <form
        name="registrationForm"
        id="form"
        #registerForm="ngForm"
        (ngSubmit)="onRegisterJobSeeker(registerForm)"
      >
        <div class="input-control">
          <div
            id="firstName-error"
            class="error"
            *ngIf="fname.touched && firstNameError"
          >
            <small>Please enter a valid first name</small>
          </div>
          <div class="user-box">
            <input
              type="text"
              ngModel
              #fname="ngModel"
              name="firstName"
              required
              class="inputField firstNameField"
              id="firstNameId"
              [(ngModel)]="firstName"
              (keyup)="validateFirstName()"
            />
            <label class="label firstNameLabel">First Name</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="lastName-error"
            class="error"
            *ngIf="lname.touched && lastNameError"
          >
            <small>Please enter a valid last name</small>
          </div>
          <div id="lastName-error"></div>
          <div class="user-box">
            <input
              ngModel
              type="text"
              name="lastName"
              required
              class="inputField lastNameField"
              id="lastNameId"
              #lname="ngModel"
              [(ngModel)]="lastName"
              (keyup)="validateLastName()"
            />
            <label class="label lastNameLabel">Last Name</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="email-error"
            class="error"
            *ngIf="emailInput.touched && emailError"
          >
            <small>Please enter a valid email</small>
          </div>
          <div id="email-error"></div>
          <div class="user-box">
            <input
              ngModel
              type="text"
              name="email"
              required
              class="inputField emailField"
              id="emailId"
              #emailInput="ngModel"
              [(ngModel)]="email"
              (keyup)="validateEmail()"
            />
            <label class="label emailLabel">Email</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="phone-error"
            class="error"
            *ngIf="phoneInput.touched && phoneError"
          >
            <small>Please enter a valid phone number</small>
          </div>
          <div id="phone-error"></div>
          <div class="user-box">
            <input
              ngModel
              type="text"
              name="phone"
              required
              class="inputField phoneField"
              id="phoneId"
              #phoneInput="ngModel"
              [(ngModel)]="phone"
              (keyup)="validatePhone()"
            />
            <label class="label phoneLabel">Phone Number</label>
          </div>
        </div>

        <div class="input-control">
          <div
            id="password-error"
            class="error"
            *ngIf="passwordInput.touched && passwordError"
          >
            <small>Please enter a password</small>
          </div>
          <div id="password-error"></div>
          <div class="user-box">
            <input
              ngModel
              type="text"
              name="password"
              required
              class="inputField passwordField"
              id="passwordId"
              #passwordInput="ngModel"
              [(ngModel)]="password"
              (keyup)="validatePassword()"
            />
            <label class="label passwordLabel">Password</label>
          </div>
        </div>

        <button
          class="submit-btn"
          role="button"
          type="submit"
          [disabled]="registerForm.invalid"
        >
          Register
        </button>
      </form>
    </div>
  </body>
</html>

// jobportal-react/src/components/Jobseeker/Jobseeker-Register/JobseekerRegister.jsx
import React, { useState } from "react";
import styles from "../../../styles/JobseekerRegister.module.css";

const JobseekerRegister = () => {
  const [formData, setFormData] = useState({});

  let [firstNameError, setFirstNameError] = useState(false);
  let [lastNameError, setLastNameError] = useState(false);
  let [emailError, setEmailError] = useState(false);
  let [phoneError, setPhoneError] = useState(false);
  let [passwordError, setPasswordError] = useState(false);

  const handleChange = (e) => {
    if (e.target.name === "firstName") {
      validateFirstName(e.target.value);
    } else if (e.target.name === "lastName") {
      validateLastName(e.target.value);
    } else if (e.target.name === "email") {
      validateEmail(e.target.value);
    } else if (e.target.name === "phone") {
      validatePhone(e.target.value);
    } else if (e.target.name === "password") {
      validatePassword(e.target.value);
    }
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    if (
      !firstNameError &&
      !lastNameError &&
      !emailError &&
      !phoneError &&
      !passwordError
    ) {
      e.preventDefault();
      console.log(formData);
    }
  };

  const validateFirstName = (firstName) => {
    if (/\d/.test(firstName)) {
      setFirstNameError(true);
    } else {
      setFirstNameError(false);
    }
  };

  const validateLastName = (lastName) => {
    if (/\d/.test(lastName)) {
      setLastNameError(true);
    } else {
      setLastNameError(false);
    }
  };

  const validateEmail = (email) => {
    if (email == "") {
      setEmailError(false);
    } else if (
      !/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
        email.toLowerCase()
      )
    ) {
      setEmailError(true);
    } else {
      setEmailError(false);
    }
  };

  const validatePhone = (phone) => {
    if (/^\d+$/.test(phone) || phone == "") {
      setPhoneError(false);
    } else {
      console.log(phone);
      setPhoneError(true);
    }
  };

  const validatePassword = (password) => {
    if (password.length < 7 && password != "") {
      setPasswordError(true);
    } else {
      setPasswordError(false);
    }
  };

  return (
    <div className={styles.modalContainer}>
      <h2>JobSeeker Register</h2>

      <form onSubmit={handleSubmit}>
        <div className="inputControl">
          {firstNameError ? (
            <div className="error">
              <div className={styles.error}>
                <p>Please enter a valid first name</p>
              </div>
            </div>
          ) : (
            <div></div>
          )}

          <div className={styles.inputBox}>
            <input
              type="text"
              className={styles.inputField}
              name="firstName"
              required
              onChange={handleChange}
            />
            <label className={styles.label}>First Name:</label>
          </div>
        </div>

        <div className="inputControl">
          {lastNameError ? (
            <div className="error">
              <div className={styles.error}>
                <p>Please enter a valid last name</p>
              </div>
            </div>
          ) : (
            <div></div>
          )}

          <div className={styles.inputBox}>
            <input
              type="text"
              className={styles.inputField}
              name="lastName"
              required
              onChange={handleChange}
            />
            <label className={styles.label}>Last Name:</label>
          </div>
        </div>

        <div className="inputControl">
          {emailError ? (
            <div className="error">
              <div className={styles.error}>
                <p>Please enter a valid email</p>
              </div>
            </div>
          ) : (
            <div></div>
          )}

          <div className={styles.inputBox}>
            <input
              type="text"
              className={styles.inputField}
              name="email"
              required
              onChange={handleChange}
            />
            <label className={styles.label}>Email:</label>
          </div>
        </div>

        <div className="inputControl">
          {phoneError ? (
            <div className="error">
              <div className={styles.error}>
                <p>Please enter a valid phone number</p>
              </div>
            </div>
          ) : (
            <div></div>
          )}

          <div className={styles.inputBox}>
            <input
              type="text"
              className={styles.inputField}
              name="phone"
              required
              onChange={handleChange}
            />
            <label className={styles.label}>Phone Number:</label>
          </div>
        </div>

        <div className="inputControl">
          {passwordError ? (
            <div className="error">
              <div className={styles.error}>
                <p>Please enter a valid password</p>
              </div>
            </div>
          ) : (
            <div></div>
          )}

          <div className={styles.inputBox}>
            <input
              type="text"
              className={styles.inputField}
              name="password"
              required
              onChange={handleChange}
            />
            <label className={styles.label}>Password:</label>
          </div>
        </div>

        <button className={styles.submitBtn} type="submit">
          Register
        </button>
      </form>
    </div>
  );
};

export default JobseekerRegister;
